# Generated by Django 3.1.3 on 2020-12-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default=' ')),
            ],
        ),
    ]
